version: "3.8"
services:
  api:
    build: .
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - REDIS_URL=${REDIS_URL}
      - HELIUS_HTTP=${HELIUS_HTTP}
      - HELIUS_WS=${HELIUS_WS}
      - LOG_LEVEL=INFO
    ports: ["8000:8000"]
    depends_on: [redis, db]
  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    ports: ["6379:6379"]
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_USER=solai
      - POSTGRES_PASSWORD=solai
      - POSTGRES_DB=solai
    ports: ["5432:5432"]
