name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest ruff mypy
      - name: Lint
        run: |
          ruff check .
          mypy --ignore-missing-imports .
      - name: Test
        run: pytest -q
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
